modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
logoFile = "assets/player-statistics/icon.png"
authors = "${mod_authors}"
credits = "FNewell for creating this mod"
displayURL = "https://github.com/FNewel/Player-statistics"
updateJSONURL = ""

[[dependencies.player-statistics]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.player-statistics]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"